 export const categories = [
  { name: "Technology" },
  { name: "Lifestyle" },
  { name: "Health" },
  { name: "Fitness" },
  { name: "Travel" },
  { name: "Food" },
  { name: "Fashion" },
  { name: "Business" },
  { name: "Finance" },
  { name: "Education" },
  { name: "Entertainment" },
  { name: "Gaming" },
  { name: "News" },
  { name: "Politics" },
  { name: "Science" },
  { name: "Environment" },
  { name: "DIY" },
  { name: "Parenting" },
  { name: "Relationships" },
  { name: "Beauty" },
  { name: "Home & Garden" },
  { name: "Sports" },
  { name: "Automotive" },
  { name: "Art & Design" },
  { name: "Photography" },
  { name: "Music" },
  { name: "Books" },
  { name: "Movies" },
  { name: "TV Shows" },
  { name: "Career" },
  { name: "Marketing" },
  { name: "Personal Development" },
  { name: "Spirituality" },
  { name: "Pets" },
  { name: "Hobbies" },
  { name: "Events" },
  { name: "Culture" },
  { name: "History" },
  { name: "Opinion" },
  { name: "Reviews" },
];
